{"name": "test_02_login_failed_by_error_username", "status": "passed", "start": 1599913603382, "stop": 1599913603471, "uuid": "f788f14f-73d3-4d2c-8080-1c7c25a92da1", "historyId": "0db325491c777d2f22cd0381dbb3c512", "testCaseId": "fcffad10266aa94222a743fd08cb2ddf", "fullName": "case.test_02_login#test_02_login_failed_by_error_username", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_02_login"}, {"name": "host", "value": "LAPTOP-CLSKU9TE"}, {"name": "thread", "value": "15976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_02_login"}]}